name: Upload gov.txt.gz from CZDS API
run-name: Upload gov.txt.gz from CZDS API

on:
  workflow_dispatch: {}
  schedule:
    - cron: "5 6 * * *"
  push:
    branches:
      - es/107-zone-file-script
    paths:
      - .github/workflows/update-gov-zone-file.yml

jobs:
  update_zone_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download gov.txt.gz
        env:
          ICANN_USERNAME: ${{ secrets.ICANN_USERNAME }}
          ICANN_PASSWORD: ${{ secrets.ICANN_PASSWORD }}
        run: |
          chmod +x ./scripts/download_zone_file.sh
          ./scripts/download_zone_file.sh ${{ env.ICANN_USERNAME }} ${{ env.ICANN_PASSWORD }}
        shell: sh
      - uses: actions/checkout@v4
      - name: Commit and push updated zone file update to branch
        run: |-
          git config user.name "Continuous Integration - Zone File"
          git config user.email "121973038+erinysong@users.noreply.github.com"
          git add ./gov.txt
          timestamp=$(date -u)
          git commit -m "Daily Zone File Update ${timestamp}" || exit 0
          git push
          
      # Uploads the .gov zone file to Github artifact gov_zone_file
      # - name: Upload retrieved .gov zone file
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: gov_zone_file
      #     path: ./gov.zone.txt
