name: Upload gov.txt.gz from CZDS API
run-name: Upload gov.txt.gz from CZDS API

on:
  schedule:
    - cron: "5 6 * * *"
  pull_request:
    branches:
      - es/107-zone-file-script
  push:
    branches:
      - es/107-zone-file-script

jobs:
  update_zone_file:
    runs-on: ubuntu-latest
    steps:
      - name: Download gov.txt.gz
        env: 
          ICANN_USERNAME: ${{ secrets[env.ICANN_USERNAME] }}
          ICANN_PASSWORD: ${{ secrets[env.ICANN_PASSWORD] }}
        run: |
          chmod +x ../../scripts/download_zone_file.sh
          ../../scripts/download_zone_file.sh ${{ secrets[env.ICANN_USERNAME] }} ${{ secrets[env.ICANN_PASSWORD] }}
        shell: sh
      # Uploads the .gov zone file to Github artifact gov_zone_file
      - name: Upload retrieved .gov zone file
        uses: actions/upload-artifact@v4
        with:
          name: gov_zone_file
          path: gov.zone.txt.gz

