name: Upload gov.txt.gz from CZDS API
run-name: Upload gov.txt.gz from CZDS API

on:
  schedule:
    - cron: "5 6 * * *"
  workflow_dispatch: {}
  pull_request:
    branches:
      - es/107-zone-file-script
  push:
    branches:
      - es/107-zone-file-script
    paths:
      - .github/workflows/update-gov-zone-file.yml

jobs:
  update_zone_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download gov.txt.gz
        env:
          ICANN_USERNAME: ${{ secrets.ICANN_USERNAME }}
          ICANN_PASSWORD: ${{ secrets.ICANN_PASSWORD }}
        run: |
          chmod +x ./scripts/download_zone_file.sh
          ./scripts/download_zone_file.sh ${{ secrets.ICANN_USERNAME }} ${{ secrets.ICANN_PASSWORD }}
        shell: sh
      # Uploads the .gov zone file to Github artifact gov_zone_file
      - name: Upload retrieved .gov zone file
        uses: actions/upload-artifact@v4
        with:
          name: gov_zone_file_update